In [2]:
import pandas as pd
import numpy as np
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.linear_model import BayesianRidge
import random

In [20]:

data = np.random.random([1000,20])
data

array([[0.13759118, 0.26405712, 0.22819585, ..., 0.43042273, 0.30799435,
        0.26187024],
       [0.48730237, 0.13104671, 0.62235968, ..., 0.5924    , 0.54451184,
        0.88435505],
       [0.54430918, 0.16859229, 0.76376755, ..., 0.51929303, 0.06241532,
        0.05419505],
       ...,
       [0.90055732, 0.10813659, 0.98993452, ..., 0.5476304 , 0.60847316,
        0.57071051],
       [0.8130049 , 0.36418512, 0.93565155, ..., 0.05273742, 0.34137124,
        0.19696307],
       [0.5666985 , 0.88981366, 0.64041033, ..., 0.72373866, 0.98807172,
        0.11174661]])

In [21]:
null_data = np.empty([1000,2])
null_data[:] = np.nan

In [22]:
null_data

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       ...,
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [23]:
full_data = np.concatenate((data,null_data), axis=1)

In [24]:
full_data

array([[0.13759118, 0.26405712, 0.22819585, ..., 0.26187024,        nan,
               nan],
       [0.48730237, 0.13104671, 0.62235968, ..., 0.88435505,        nan,
               nan],
       [0.54430918, 0.16859229, 0.76376755, ..., 0.05419505,        nan,
               nan],
       ...,
       [0.90055732, 0.10813659, 0.98993452, ..., 0.57071051,        nan,
               nan],
       [0.8130049 , 0.36418512, 0.93565155, ..., 0.19696307,        nan,
               nan],
       [0.5666985 , 0.88981366, 0.64041033, ..., 0.11174661,        nan,
               nan]])

In [29]:
np.random.permutation(full_data.flat)

array([0.69262441,        nan, 0.61474898, ..., 0.33718017, 0.46763913,
       0.41346398])

In [30]:
full_data.shape

(1000, 22)

In [32]:
imputer = IterativeImputer(BayesianRidge())
impute_data = pd.DataFrame(imputer.fit_transform(full_data))

In [33]:
impute_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.802099,0.081094,0.681566,0.283155,0.636927,0.144221,0.329944,0.829943,0.536491,0.542645,0.347444,0.986985,0.429133,0.190686,0.714384,0.898292,0.340325,0.490459,0.813119,0.002028
1,0.505521,0.842660,0.394852,0.819314,0.715554,0.065629,0.225661,0.453985,0.541598,0.077837,0.795040,0.478940,0.753428,0.586249,0.413235,0.571023,0.109003,0.365899,0.637131,0.427606
2,0.031690,0.859672,0.291117,0.852825,0.309727,0.905307,0.684518,0.547853,0.993550,0.748999,0.061146,0.234953,0.834106,0.887064,0.039257,0.801913,0.353594,0.562102,0.853629,0.954255
3,0.786855,0.022223,0.642325,0.669138,0.443158,0.029588,0.553646,0.751210,0.410222,0.954615,0.022457,0.519803,0.529622,0.091029,0.173809,0.407648,0.047332,0.632186,0.341228,0.427072
4,0.110549,0.898562,0.909027,0.877121,0.210213,0.830342,0.680397,0.746326,0.134144,0.455458,0.078429,0.053358,0.653408,0.651493,0.248172,0.013197,0.084533,0.743751,0.638978,0.331249

In [34]:
impute_data.isnull()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False